#!/bin/sh /etc/rc.common

USE_PROCD=1
START=100
STOP=01

CONFIGURATION=public_ip_monitor

start_service() {
    # Read the config
    config_load "${CONFIGURATION}"

    local monitor_ip
    local ip_service
    local ip_check_interval
    local ip_script_location

    # start retrieving ipv6 monitor configs
    config_get monitor_ip general monitor_ipv6
    config_get ip_service general ipv6_ip_service
    config_get ip_check_interval general ipv6_check_interval
    config_get ip_script_location general ipv6_script_location

    local history_location

    # retrieve location history
    config_get history_location general history_location

    # start procd configuration

    if [ "$monitor_ip" == "1" ]; then
        procd_open_instance
        procd_set_param command /bin/sh "/var/pimonitor.sh" "IPv6" "public_ip_monitor.ipv6.current" "${ip_service}" "${ip_check_interval}" "${ip_script_location}" "${history_location}"

        procd_set_param file /etc/config/public_ip_monitor

        procd_set_param stdout 1
        procd_set_param stderr 1

        procd_close_instance
    fi
    
}

service_triggers() {
    procd_add_reload_trigger "public_ip_monitor"
}